version: "3"

services:
  db:
    container_name: cloudlockr_db
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - database.env

  redis:
    container_name: cloudlockr_redis
    image: redis
    ports:
      - "6000:6379"
